
default : all

ifeq ($(USE_VERILATOR),)

all :
	iverilog -t vvp -o test.vvp two2one_multiplexor.v two2one_multiplexor_tb.v
	vvp test.vvp

clean :
	rm -f *.vcd *.vvp

else

all :
	verilator --binary --trace --top test two2one_multiplexor.v two2one_multiplexor_tb.v
	obj_dir/Vtest

clean :
	rm -rf obj_dir

endif
